/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-12-02 01:46:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" //jquery 로 간단하게 유효성 check 하기\r\n");
      out.write("  function check(){\r\n");
      out.write("	 var firstNumber = joinForm.firstNumber.value;\r\n");
      out.write("	 \r\n");
      out.write("	 if(!joinForm.userid.value){\r\n");
      out.write("		 alert('ID를 입력해 주세요.');\r\n");
      out.write("		 joinForm.userid.focus();\r\n");
      out.write("		 return false;\r\n");
      out.write("	 }else if(!joinForm.pwd.value){\r\n");
      out.write("		 alert('PWD를 입력해 주세요.');\r\n");
      out.write("		 joinForm.pwd.focus();\r\n");
      out.write("		 return false;\r\n");
      out.write("	 }else if(!joinForm.name.value){\r\n");
      out.write("		 alert('name를 입력해 주세요.');\r\n");
      out.write("		 joinForm.name.focus();\r\n");
      out.write("		 return false;\r\n");
      out.write("	 }else if(!joinForm.firstEmail.value){\r\n");
      out.write("		 alert('이메일을 확인해주세요');\r\n");
      out.write("		 joinForm.firstEmail.focus();\r\n");
      out.write("		 return false;\r\n");
      out.write("	 }else if(!joinForm.lastEmail.value){\r\n");
      out.write("		 alert('이메일을 확인해주세요');\r\n");
      out.write("		 joinForm.lastEmail.focus();\r\n");
      out.write("		 return false;\r\n");
      out.write("	 }else if(firstNumber === \"First Number\"){\r\n");
      out.write("		 alert('핸드폰 앞자리를 입력해 주세요.');\r\n");
      out.write("		 joinForm.firstNumber.focus();\r\n");
      out.write("		 return false;\r\n");
      out.write("	 }else if(!joinForm.phoneNumber.value){\r\n");
      out.write("		 alert('핸드폰번호를 입력해 주세요.');\r\n");
      out.write("		 joinForm.phoneNumber.focus();\r\n");
      out.write("		 return false;\r\n");
      out.write("	 }\r\n");
      out.write("	 document.joinForm.submit();\r\n");
      out.write(" } \r\n");
      out.write(" \r\n");
      out.write(" function submit2(frm) { \r\n");
      out.write("	    frm.action='idOverlapCheck.user'; \r\n");
      out.write("	    frm.submit(); \r\n");
      out.write("	    return true; \r\n");
      out.write("	  } \r\n");
      out.write("\r\n");
      out.write(" $(function(){\r\n");
      out.write("	//아이디 중복확인 비동기 \r\n");
      out.write("	$('#idcheck').on(\"click\",(function(){//checkView\r\n");
      out.write("		\r\n");
      out.write("		//비동기 함수 호출\r\n");
      out.write("		 	$.ajax({\r\n");
      out.write("				url : \"idOverlapCheck.user\",  //URL 보내기\r\n");
      out.write("				type : \"POST\",					 //방식\r\n");
      out.write("				dataType : \"html\",		  	 //데이터 타입\r\n");
      out.write("				data : {\r\n");
      out.write("					'userid' : $('#userid').val()  //글번호 \r\n");
      out.write("				},\r\n");
      out.write("				success : function(data){\r\n");
      out.write("				$('#checkView').empty(data);\r\n");
      out.write("				$('#checkView').append(data);\r\n");
      out.write("				},\r\n");
      out.write("				error : function(request,status,error){\r\n");
      out.write("					alert(\"code:\" +request.status+\"\\n\" + \"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("					console.log(error);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("	}));\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>DASHMIN - Bootstrap Admin Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("<link href=\"images/kingbird.ico\" rel=\"icon\">\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    input {\r\n");
      out.write("    	marin-top:10px;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("		<!-- 사이드바 들어갈 자리 -->\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/sidebar_css.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- 사이드바 들어갈 자리 -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("        <!-- 헤더 -->\r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/header_css.jsp", out, false);
      out.write("\r\n");
      out.write("		<!-- 헤더 -->\r\n");
      out.write("\r\n");
      out.write("         <!-- \r\n");
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("          -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Sign Up Start -->\r\n");
      out.write("          <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row h-100 align-items-center justify-content-center\" style=\"min-height: 100vh;\">\r\n");
      out.write("                <div class=\"col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4\" style=\"width:800px; padding-top:40px;\">\r\n");
      out.write("                    <div class=\"bg-light rounded p-4 p-sm-5 my-4 mx-3\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                            <a href=\"index.do\">\r\n");
      out.write("                                <h3 class=\"text-primary\" style=\"margin-left:20px;\">KINGBIRD</h3>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <h4 style=\"margin-left:50px;\">Sign Up</h4>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("               \r\n");
      out.write("                        <form action=\"insert.do\" method=\"post\" name=\"joinForm\" id=\"joinForm\" novalidate>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"col-sm-12 col-xl-6\">\r\n");
      out.write("                        <div class=\"bg-light rounded h-100 p-4\" style=\"width:600px; padding-top:40px;\">\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"userid\" id=\"userid\" placeholder=\"ID를 입력하세요\"\r\n");
      out.write("                                    aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                                <span class=\"input-group-text\" id=\"basic-addon2\"><button type=\"button\" class=\"btn btn-primary rounded-pill m-2\" value='ID중복확인' id=\"idcheck\">ID중복확인</button></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div id=\"checkView\"></div>\r\n");
      out.write("                            <div class=\"input-group mb-3\">\r\n");
      out.write("                                <span class=\"input-group-text\" id=\"basic-addon1\">Password</span>\r\n");
      out.write("                                <input class=\"form-control\" type=\"password\" name=\"pwd\" id=\"pwd\" placeholder=\"Password를 입력하세요\" aria-label=\"pwd 입력\"\r\n");
      out.write("                                    aria-describedby=\"basic-addon1\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"input-group mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" name=\"firstEmail\" id=\"firstEmail\" placeholder=\"E-mail\"\r\n");
      out.write("                                    aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                                <span class=\"input-group-text\" id=\"basic-addon2\">\r\n");
      out.write("                                <select class=\"form-select\" id=\"lastEmail\" name=\"lastEmail\" aria-label=\"Floating label select example\">\r\n");
      out.write("                                    <option selected>Last E-mail</option>\r\n");
      out.write("                                    <option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("                                    <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("                                    <option value=\"hanmail.com\">hanmail.com</option>\r\n");
      out.write("                                </select></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group mb-3\">\r\n");
      out.write("                                <span class=\"input-group-text\" id=\"basic-addon1\">이름</span>\r\n");
      out.write("                                <input type=\"text\" name=\"name\" id=\"name\" class=\"form-control\" placeholder=\"이름을 입력하세요\" aria-label=\"이름 입력\"\r\n");
      out.write("                                    aria-describedby=\"basic-addon1\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group mb-3\">\r\n");
      out.write("                                <span class=\"input-group-text\" id=\"basic-addon1\"><select class=\"form-select\" id=\"firstNumber\" name=\"firstNumber\"\r\n");
      out.write("                                    aria-label=\"Floating label select example\">\r\n");
      out.write("                                    <option selected>First Number</option>\r\n");
      out.write("                                    <option value=\"010\">010</option>\r\n");
      out.write("                                    <option value=\"016\">016</option>\r\n");
      out.write("                                    <option value=\"011\">011</option>\r\n");
      out.write("                                </select></span>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"전화번호를 입력하세요\" name=\"phoneNumber\" id=\"phoneNumber\"\r\n");
      out.write("                                    aria-describedby=\"basic-addon1\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <label for=\"your Gender\">Your Gender </label>\r\n");
      out.write("                             <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"gender\" value=\"여\" checked>\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexRadioDefault2\">\r\n");
      out.write("                                    여성\r\n");
      out.write("                                </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"gender\" value=\"남\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexRadioDefault2\">\r\n");
      out.write("                                    남성\r\n");
      out.write("                                </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"input-group mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"자주 사용하시는 개발언어를 선택해주세요\"\r\n");
      out.write("                                    aria-label=\"Recipient's username\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("                                <span class=\"input-group-text\" id=\"basic-addon2\"><select class=\"form-select\" id=\"floatingSelect\"\r\n");
      out.write("                                    aria-label=\"Floating label select example\">\r\n");
      out.write("                                    <option selected>JAVA</option>\r\n");
      out.write("                                    <option value=\"1\">C++</option>\r\n");
      out.write("                                    <option value=\"2\">javascript</option>\r\n");
      out.write("                                    <option value=\"3\">C+</option>\r\n");
      out.write("                                </select></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div align=\"center\">\r\n");
      out.write("                            	 <button type=\"button\" class=\"btn btn-primary rounded-pill m-2\" onclick=\"check();\">회원가입</button>\r\n");
      out.write("                        	아이디가 있으신가요? <a href=\"login.do\"> Log in</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                      </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("                  \r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("        </div> \r\n");
      out.write("        \r\n");
      out.write("        <!-- Sign Up End -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Footer Start -->\r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer_css.jsp", out, false);
      out.write("\r\n");
      out.write("            <!-- Footer End -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Content End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Back to Top -->\r\n");
      out.write("        <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/chart/chart.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
